### ISSUE TITLE
internal error at /departments/{departmentId}/courses

### ISSUE THREAD

**Issue by zetaraku** [NCU-CC/API-Documentation#17]
/departments/{departmentId}/courses has an internal server error.
Besides, the link on API menu may be type as "/departments/{departmentId}/courses" not "/departments/{departmentId}"

error_description
500 Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [Source:

**Comment by jason1122g** [comment]
thank you for your response 

this problem has been reported to the person in charge

**Comment by yyc1217** [comment]
solved
