### ISSUE TITLE
OAuth 註冊應用服務 失敗

### ISSUE THREAD

**Issue by davy-tw** [NCU-CC/API-Documentation#18]
https://www.youtube.com/watch?v=xFGcQi7yK9A&feature=youtu.be 
如影片中所示，無論如何填寫資料都顯示「系統存取錯誤」

這樣要如何使用你們的服務？

**Comment by davy-tw** [comment]
結果進入 「應用服務管理」 之後看到有好多個重複嘗試的應用服務……
意思是我成功了但是系統顯示失敗？

**Comment by jason1122g** [comment]
已回報負責人員

**Comment by yyc1217** [comment]
fixed.
