### ISSUE TITLE
How can I get user unique id?

### ISSUE THREAD

**Issue by davy-tw** [NCU-CC/API-Documentation#20]
In document `https://github.com/NCU-CC/API-Documentation/blob/master/personnel-service/v1/cards.md#structure`, we only can get the name of person and their unit and group or title.
So, can I get the unique id of each person that I can binding and recognize everyone in this system?

**Comment by jason1122g** [comment]
`number` field of student is the unique id

there is no unique id of faculty  currently

this problem will be solved as soon as possible

**Comment by jason1122g** [comment]
@david50407  this feature is online now

**Comment by davy-tw** [comment]
@jason1122g Thanks. But which field is the unique id? `number` ?
BTW, there is a typo here in `card.md`:

```
"number" : "F123456"",
```

should be

```
"number" : "F123456",
```

**Comment by jason1122g** [comment]
fixed

**Comment by yyc1217** [comment]
@david50407, we add id field now, so use

```
"id" : "F123456"
```

instead of

```
"number" : "F123456"
```
